"""NOVA configuration — API keys and settings."""

# API Keys
ANTHROPIC_API_KEY = "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"
OPENAI_API_KEY = "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"
ELEVENLABS_API_KEY = "sk_2d73e84b25da7d9bde62e74a0d0fe6a9021e3f3dc6de6b92"
ELEVENLABS_VOICE_ID = "21m00Tcm4TlvDq8ikWAM"  # Rachel; use pNInz6obpgDQGcFmaJgB for Adam

# APEX
APEX_RAILWAY_URL = "https://apex-production-b5bc.up.railway.app"
APEX_LIVE_START_CAPITAL = 96908.79
APEX_LIVE_START_DATE = "2026-06-01"

# Hotkey and audio
ACTIVATION_HOTKEY = "cmd+j"
HOTKEY_COOLDOWN_SECONDS = 3
RECORDING_DURATION_SECONDS = 5
SESSION_TIMEOUT = 30
MAX_RESPONSE_TOKENS = 300
CONVERSATION_MEMORY_LENGTH = 5

# Identity
NOVA_NAME = "NOVA"
USER_NAME = "Kian"

# Audio recording
SAMPLE_RATE = 16000

# API caching (seconds)
BACKTEST_CACHE_SECONDS = 60
LIVE_CACHE_SECONDS = 30

# Claude
CLAUDE_MODEL = "claude-sonnet-4-20250514"

# ElevenLabs
ELEVENLABS_MODEL = "eleven_monolingual_v1"
ELEVENLABS_STABILITY = 0.75
ELEVENLABS_SIMILARITY_BOOST = 0.75

# Paths
MEMORY_FILE = "nova_memory.json"
ERROR_LOG_FILE = "nova_errors.log"
